#èœå•
menu:
  Home: /
  Post: /post

#ç¤¾äº¤é“¾æ¥
link:
  -
    name: Github
    url: https://github.com/sooooooooooooooooootheby
    icon: github2

#ä¸»é¡µä»‹ç»
homeIntroduce:
  one: ~Wonderland~
  p1: Welcome my blogğŸ‘‹
  p2: This is my best Website

# ä¸»é¡µæŒ‰é’®
homeButton:
  -
    name: cancan my repositories
    url: https://github.com/sooooooooooooooooootheby
    buttonType: brand

#ä¸»é¡µå®¹å™¨
homeContainer:
  -
    svg: HTML
    span: HTMLã€CSSã€Javascript
    p: å‰ç«¯ä¸‰ä»¶å¥—è¾£
  -
    svg: Vue
    span: Vue.js
    p: æ¸è¿›å¼JavaScript æ¡†æ¶ã€‚æ˜“å­¦æ˜“ç”¨ï¼Œæ€§èƒ½å‡ºè‰²ï¼Œé€‚ç”¨åœºæ™¯ä¸°å¯Œçš„ Web å‰ç«¯æ¡†æ¶ã€‚
  -
    svg: GSAP
    span: GSAP
    p: ä¸ºä¸“ä¸šäººå£«æ„å»ºçš„éå¸¸å¥å£®çš„JavaScriptåŠ¨ç”»åº“
  -
    svg: stylus
    span: stylus
    p: ä¸€ä¸ªå¯Œäºè¡¨ç°åŠ›ã€åŠ¨æ€çš„ã€å¥å£®çš„CSSé¢„å¤„ç†å™¨ã€‚
  -
    svg: sass
    span: sass
    p: ä¸–ç•Œä¸Šæœ€æˆç†Ÿã€æœ€ç¨³å®šã€æœ€å¼ºå¤§çš„ä¸“ä¸šçº§CSSæ‰©å±•è¯­è¨€ï¼

# é¡µè„š
# ç«™ç‚¹
footerWebsite:
  -
    name: Alice's SourceGather
    url: https://tool.sooooooooooooooooootheby.xyz/
    img: https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/%E5%8F%8B%E9%93%BE%2FGCI66_OWsAEcqFY.webp
# å‹é“¾
footerfriend:
  -
    name: 'â™¥DDåˆ›â™¥'
    url: https://www.woodude.top/
    img: https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/%E5%8F%8B%E9%93%BE%2Ffavicon.webp

# è¡¨æƒ…åŒ…
meme:
  FRICKMeNot: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FFRICKMeNot.png'
  MatildaDizzy: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FMatildaDizzy.png'
  MatildaSob: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FMatildaSob.png'
  MatildaSumug: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FMatildaSumug.png'
  MedPoc_Sip: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FMedPoc_Sip.png'
  Nodnetto: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FNodnetto.gif'
  OMEGULUS: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FOMEGULUS.png'
  RegulusDance: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FRegulusDance.gif'
  RegulusHeh: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FRegulusHeh.png'
  RegulusNanikore: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FRegulusNanikore.png'
  RegulusWheeze: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FRegulusWheeze.png'
  RegulusWow: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FRegulusWow.png'
  RegulusYay: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FRegulusYay.png'
  SchneiderWeird: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FSchneiderWeird.png'
  SonettoHeart: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FSonettoHeart.png'
  SothebyTehe: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FSothebyTehe.png'
  SothebyUnion: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FSothebyUnion.png'
  SpathodeaWisdom: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FSpathodeaWisdom.png'
  VerFear: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FVerFear.png'
  VertinAngy: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FVertinAngy.png'
  VertinLike: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FVertinLike.png'
  VertinPunch: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FVertinPunch.gif'
  VertinSleep: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2FVertinSleep.png'
  anansquish: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2Fanansquish.png'
  charlieworried: 'https://blogimage-1315833212.cos.ap-shanghai.myqcloud.com/meme%2Fcharlieworried.png'

# Valineè¯„è®ºç³»ç»Ÿ
valine:
  appid: oiMwEQjnLkcATBsd7rmnxwCf-gzGzoHsz
  appkey: nxYKJ10KXUR23EROEtXI3qBK
  placeholder: æ˜µç§°å¡«å†™QQå·å¯ä»¥è·å–åˆ°ä½ çš„QQå¤´åƒ,å¦‚æœä½ æœ‰Gravatarå¯ä»¥å¡«å†™æ³¨å†ŒGravataræ‰€ç”¨çš„é‚®ç®±å·,å°±å¯ä»¥è·å–ä½ Gravatarçš„å¤´åƒäº†ã€‚é‚®ç®±é€šçŸ¥ç³»ç»Ÿä¸€ç›´æ•´ä¸ä¸Š,æ‰€ä»¥å¦‚æœéœ€è¦å›å¤éº»çƒ¦é¢å¤–ç•™ä¸€ä¸‹é‚®ç®±å·(